# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_official_gene_symbol": "00_core.ipynb",
         "get_gene_id": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://broadinstitute.github.io/update_gs_hgnc/"

git_url = "https://github.com/broadinstitute/update_gs_hgnc/tree/master/"

def custom_doc_links(name): return None
