# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_official_gene_symbol', 'get_gene_id']

# Cell
import requests, sys

def get_official_gene_symbol(gs):
    """Get official gene symbol from HGNC
    :param gs: str, gene symbol
    :return: off_gs, official HGNC gene symbol
    """
    gene_id = get_gene_id(gs)
    if gene_id != '':
        server = "https://rest.ensembl.org/"
        ext = 'xrefs/id/'+gene_id+'?all_levels=1;external_db=HGNC'
        r = requests.get(server+ext, headers={ "Content-Type" : "application/json"})
        if not r.ok:
            r.raise_for_status()
            sys.exit("Gene not found")
        gene_info = r.json()
        off_gs = gene_info[0]['display_id']
        return off_gs
    else:
        print('Gene not found')

def get_gene_id(gs):
    """Get Ensembl gene ID of symbol
    :param gs: str, gene symbol
    :return: gene_id, Ensembl gene ID
    """
    server = "https://rest.ensembl.org/"
    ext = 'xrefs/symbol/homo_sapiens/'+gs+'?external_db=HGNC;feature_type=gene;all_levels=1;'
    r = requests.get(server+ext, headers={ "Content-Type" : "application/json"})
    if not r.ok:
        r.raise_for_status()
        sys.exit("Gene not found")
    gene_info = r.json()
    if len(gene_info)>0:
        gene_id = gene_info[0]['id']
        return gene_id
    else:
        return ''